#version 430
layout (local_size_x = 160, local_size_y = 9, local_size_z = 1) in;
layout (rgba32f, binding = 4) uniform image3D imgInput;
layout (rgba32f, binding = 5) uniform image3D imgOutput;

void main()
{
	const uint texDepth = 64;
	for (uint z = 0; z < texDepth; ++z)
	{
		const ivec3 coords = ivec3(gl_GlobalInvocationID.xy, z);
		const vec4 colour = imageLoad(imgInput, coords);

		imageStore(imgOutput, coords, colour);
	}
}